1.Create 2D numpy array using arange() function

In [1]:
import numpy as np
a=np.arange(2,10).reshape(2,4)
print(a)

[[2 3 4 5]
 [6 7 8 9]]


2.Create 3D array from 1D numpy array

In [2]:
import numpy as np

a=[1,2,3]
b=[4,5,6]
c=[7,8,9]

d=np.array([a,b,c])
print("Method 1 : \n",d)

a1=np.arange(1,10).reshape(3,3)
print("Method 2 : \n",a1)



Method 1 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Method 2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [3]:
import numpy as np

array=np.arange(2,11).reshape(3,3)

print(array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


4.Write a NumPy program to reverse an array (first element becomes last)

In [4]:
import numpy as np

array=np.arange(2,10)
print("Array = {} ".format(array))

rearray=array[::-1]
print("Reverse of Array = {} ".format(rearray))

Array = [2 3 4 5 6 7 8 9] 
Reverse of Array = [9 8 7 6 5 4 3 2] 


5.Write a NumPy program to create a 2d array with 1 on the border and 0 inside

In [5]:
import numpy as np
array = np.ones((4,4))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


6.Create a 2D array A with 4x4 size then split it into 3 different arrays B(1x4),C(2x4) and D(2x4).

In [6]:
import numpy as np

array=np.arange(1,17).reshape(4,4)
print(array)
A=array[0:1]
B=array[0:2]
C=array[2:]
print("A = ",A)
print("B =",B)
print("C =",C)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
A =  [[1 2 3 4]]
B = [[1 2 3 4]
 [5 6 7 8]]
C = [[ 9 10 11 12]
 [13 14 15 16]]


7.Perform element wise multiplication of arrays C and B in question 6.

In [7]:
multy=np.multiply(B,C)
print(multy)

[[  9  20  33  48]
 [ 65  84 105 128]]


8.Create a numpy array matrix of size 3x4. Find column which has highest sum and display

In [8]:
import numpy as np
array=np.arange(1,13).reshape(3,4)
asum=array.sum(axis=0)
print("Sum of column is = ",asum)
print(max(asum))

Sum of column is =  [15 18 21 24]
24
